export const ADD_STARRATING = 'ADD_STARRATING'
export const ADD_MOODS = 'ADD_MOODS'
export const ADD_REVIEW = 'ADD_REVIEW'
export const SUBMIT_REVIEW = 'SUBMIT_REVIEW'
export const RESET_VERSION1 = 'RESET_VERSION1'

export const ADD_STARRATING_2 = 'ADD_STARRATING_2'
export const ADD_MOODS_2 = 'ADD_MOODS_2'
export const ADD_REVIEW_2 = 'ADD_REVIEW_2'
export const SUBMIT_REVIEW_2 = 'SUBMIT_REVIEW_2'
export const RESET_VERSION2 = 'RESET_VERSION2'

